all: heapsort quicksort mergesort heapsortForString quicksortForString mergesortForString
heapsort: heapsort.c heapsort.h
	gcc heapsort.c -o heapsort
mergesort: mergesort.c mergesort.h
	gcc mergesort.c -o mergesort
quicksort: quicksort.c quicksort.h
	gcc quicksort.c -o quicksort
heapsortForString: heapsortForString.c heapsortForString.h
	gcc heapsortForString.c -o heapsortForString
quicksortForString: quicksortForString.c quicksortForString.h
	gcc quicksortForString.c -o quicksortForString
mergesortForString: mergesortForString.c mergesortForString.h
	gcc mergesortForString.c -o mergesortForString
clean:
	rm heapsort mergesort quicksort heapsortForString quicksortForString mergesortForString
